---
- name: dependency provisioning
  hosts: all
  become: yes
  become_method: sudo
  gather_facts: false
  tasks:
    - raw: sudo apt-get update
    - name: install python2
      raw: sudo apt-get -y install python-minimal

- hosts: all
  become: yes
  become_user: root
  tasks:
    - name: install aptitude
      apt: 
        name: aptitude
        state: present

    - name: Upgrade to latest debian packages
      apt:
        upgrade: yes
        update_cache: yes   

    - name: Install Required Packages
      apt: 
        name: ['git', 'vim', 'jq', 'parted', 'e2fsprogs', 'python3', 'python3-pip', 'dos2unix', 'nginx', 'unzip']

    - name: copy viabtc_xch.zip
      copy:
        src: ../viabtc_xch.zip
        dest: /opt/viabtc_xch.zip

    - name: extract viabtc_xch.zip
      shell: unzip -o /opt/viabtc_xch.zip -d {{root_dir}}

- import_playbook: firewall.yml
  when: deploy_type != "local"
- import_playbook: updates.yml
  when: deploy_type != "local"
- import_playbook: fail2ban.yml
  when: deploy_type != "local"
- import_playbook: logwatch.yml
  when: deploy_type != "local"
- import_playbook: postfix.yml
  when: deploy_type != "local"
- import_playbook: mysql.yml
- import_playbook: redis.yml
- import_playbook: kafka.yml
- import_playbook: match_svr.yml
- import_playbook: price_svr.yml
- import_playbook: data_svr.yml
- import_playbook: http_svr.yml
- import_playbook: ws_svr.yml
- import_playbook: alert_svr.yml
- import_playbook: backup.yml
