---
- hosts: all
  become: true
  gather_facts: False
  pre_tasks:
    # Ansible requires python2, which is not installed by default on Ubuntu Xenial
    - raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
    # action: setup will gather facts after python2 has been installed
    - action: setup
  tasks:

    - import_tasks: build_viaxch.yml

    - name: create log directory
      file: path=/var/log/trade/ state=directory

    - name: copy conf file
      shell: mkdir -p {{conf_dir}}/accesshttp; cp {{root_dir}}/accesshttp/config.json {{conf_dir}}/accesshttp/config.json

    # using named groups due to ansible munging backrefs next to numbers (http://www.handverdrahtet.org/2016/01/ansible-using-numbered-backreference.html)
    - name:
      shell: perl -i -p0e 's/{{ item.regexp }}/{{ item.replace }}/s' {{conf_dir}}/accesshttp/config.json
      with_items:
          - { regexp: '(?<one>"matchengine": \{[^\{]*"addr": \[[^\{]*"tcp@)(127.0.0.1)(?<three>:7316")',
              replace: '$+{one}{{match_host}}$+{three}' }
          - { regexp: '(?<one>"marketprice": \{[^\{]*"addr": \[[^\{]*"tcp@)(127.0.0.1)(?<three>:7416")',
              replace: '$+{one}{{price_host}}$+{three}' }
          - { regexp: '(?<one>"readhistory": \{[^\{]*"addr": \[[^\{]*"tcp@)(127.0.0.1)(?<three>:7424")',
              replace: '$+{one}{{data_host}}$+{three}' }
          - { regexp: '(?<one>"alert": \{[^\{]*"addr": ")(127.0.0.1)(?<three>:4444")',
              replace: '$+{one}{{alert_host}}$+{three}' }

    - name: install accesshttp systemd service
      template: src=templates/accesshttp.j2 dest=/etc/systemd/system/accesshttp.service

    - name: stop accesshttp
      systemd: state=stopped name=accesshttp
      ignore_errors: yes

    - name: start accesshttp
      systemd: state=started enabled=yes name=accesshttp daemon_reload=yes
