---
- hosts: all
  vars:
    redis_port: 6379
    sentinel_port: 26381
  become: true
  gather_facts: False
  pre_tasks:
    # Ansible requires python2, which is not installed by default on Ubuntu Xenial
    - raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
    # action: setup will gather facts after python2 has been installed
    - action: setup
  tasks:

   - name: install the redis packages
     apt:
       name: ['redis-server', 'redis-sentinel', 'redis-tools']

   - name: add redis.local.conf template
     template: src=templates/redis.local.conf.j2 dest=/etc/redis/redis.local.conf group=redis owner=redis

   - name: add sentinel.local.conf template
     template: src=templates/sentinel.local.conf.j2 dest=/etc/redis/sentinel.local.conf group=redis owner=redis

   - name: add redis.local.conf include to redis.conf
     lineinfile:
       dest: /etc/redis/redis.conf
       line: 'include /etc/redis/redis.local.conf'

   - name: replace sentinel.conf monitor conf
     replace:
       dest: /etc/redis/sentinel.conf
       regexp: '^sentinel monitor mymaster 127.0.0.1 6379 2'
       replace: 'sentinel monitor mymaster {{ redis_host }} {{ redis_port }} 1'

   - name: add sentinel.local.conf include to sentinel.conf
     lineinfile:
       dest: /etc/redis/sentinel.conf
       line: 'include /etc/redis/sentinel.local.conf'

   - name: restart redis
     service: name=redis state=restarted

   - name: restart redis sentinel
     service: name=redis-sentinel state=restarted
